fristcommit
nixon0290211/app.py pull request #1
Opened 2022-11-07 10:26 UTC by nixon0290211

2022-11-08 01:42 UTC, kzri4 commented on app.py
> +pyautogui.hotkey("space", "Enter", "Enter")
pcの性能次第かもしれませんが、ブラウザで検索してページが表示される前にスクリーンショットが撮られてしまうようなので、スクショまでに少し間を空けるようにしてみてください👍

2022-11-08 01:42 UTC, kzri4 commented on app.py
> +pyautogui.press("u")
ローマ字を全て打つのも1つの手ですが、　長いコードになってしまうので、日本語でそのまま入力できるように調べて、実装してみてください👍

2022-11-09 13:36 UTC, kazu-taka requested changes
@nixon0290211 
コメントしたので確認お願いします:bow:

2022-11-09 13:36 UTC, kazu-taka commented on app.py
> +pyautogui.hotkey("command", "v")
@nixon0290211 
テスト結果のスクリーンショットを見ると、検索結果のページがうまく撮れていないようです！
また、検索するキーワードは、「平泉町 観光」になるので修正お願いします🙏
また、私のところではうまくhotkeyが動かなかったので、keyDownやpressを組み合わせて貼り付けしてみて下さい✨

2022-11-10 00:21 UTC, kzri4 commented on app.py
> +pyautogui.hotkey("Ctrl", "v")
hotkeyが動かない場合は、以下のように組み合わせて試してみてください👍

```
 pyautogui.keyDown("command")
 pyautogui.press("v")
```

2022-11-10 00:27 UTC, nixon0290211 commented on app.py
> +pyautogui.hotkey("Ctrl", "v")
ありがとうございます😊

2022-11-11 13:32 UTC, merged